### ISSUE TITLE
记录一次github CI流水线配置

### ISSUE THREAD

**Issue by beikeliu** [beikeliu/MyBlog#2]
两个关键点，一个token，一个配置文件。

配置文件：
```yml
# 当前项目下.github/workflows
name: Build and Deploy
on:
  push:
    branches:
      - master # 从哪个分支git push触发执行 
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 构建文件在哪个目录
          token: ${{ secrets.TOKEN }} # 使用哪个TOKEN
```

生成token：https://github.com/settings/tokens
使用token：https://github.com/<你的GitHub username>/<你的Github Project Name>/settings/secrets/actions
